# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - README.md
  - README
  - README.markdown
  - README.txt
  - node_modules/brace-expansion/README.md
  - node_modules/fsevents/node_modules/brace-expansion/README.md
  - node_modules/fsevents/node_modules/balanced-match/README.md
  - node_modules/the-graph/node_modules/brace-expansion/README.md
  - node_modules/the-graph/node_modules/balanced-match/README.md
  - node_modules/the-graph/node_modules/decode-uri-component/readme.md
  - Dockerfile
  - Gruntfile.js
  - package.json
  - package-lock.json
  - README.md
#   - Gemfile
#   - Gemfile.lock
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
